env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - task update-version-file

universal_binaries:
  - replace: false

archives:
  - format_overrides:
      - goos: windows
        format: zip

builds:
  - main: ./cmd/laravel-make
    binary: 'laravel-make'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.build={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

signs:
  - artifacts: checksum

checksum:
  name_template: "checksums.txt"
  algorithm: sha256
