env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
    - go mod tidy
    - task update-version-file

universal_binaries:
  - replace: false

archives:
  - id: default
    wrap_in_directory: true
  - format_overrides:
      - goos: windows
        format: zip

builds:
  - main: ./cmd/laravel-make
    binary: 'laravel-make'
    flags:
      - -trimpath

    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X main.build={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64
      - arm64

# brews:
#   -
#     name: 'laravel-make'
#     homepage: 'https://github.com/permafrost-dev/laravel-make'
#     description: 'Scaffold a new Laravel project'
#     license: "MIT"
#     tap:
#       owner: 'permafrost-dev'
#       name: homebrew-laravel-make
#       branch: main

signs:
  - artifacts: checksum

checksum:
  name_template: "checksums.txt"
  algorithm: sha256
