name: run-goreleaser

on:
  push:
    # run only against tags
    tags:
      - 'v*'

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  artifact-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Install Go
        uses: WillAbides/setup-go-faster@v1.8.0
        with:
          go-version: '>=1.20'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --skip-docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
